---
title: "Hacking for Historians"
subtitle: "An Introduction to Digital History with R"
author: "Matthias Bannert** (@whatsgoodio) and Ina Serif++"
institute: "ETH Zurich**, Uni Basel++"
date: "2019-09-25"
output:
  xaringan::moon_reader:
    css: ["robot-fonts","more.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

---

## teachers:~$ whoami

.pull-left[

### Matthias Bannert ([@whatsgoodio](https://twitter.com/whatsgoodio))

- Data DevOps @KOF, ETH Zurich 
- PhD in Economics 
- 20+ years programming experience
 
]

.pull-right[

### Ina Serif ([@wissen_ist_acht](https://twitter.com/wissen_ist_acht))

- assistant/post doc, Uni Basel
- PhD in Medieval History; digital historian
- 20+ hrs programming experience

]

**course material**: [github.com/mbannert/dh-2019](https://github.com/mbannert/dh-2019)



---

class: center, middle

## Who Are You?

---

class: center, middle

## Why Would a Historian Want to Program? 

<!--
Show demos
1. API examples
2. visualization 
3. Text Mining & Regular Expressions
-->


---


## Why Would a Historian Want to Program? 


- Access to Data Sources (**A**pplication **P**rogramming **I**nterfaces) 



---


## Why Would a Historian Want to Program? 


- Access to Data Sources (**A**pplication **P**rogramming **I**nterfaces) 

- Visualization


---


## Why Would a Historian Want to Program? 


- Access to Data Sources (**A**pplication **P**rogramming **I**nterfaces) 

- Visualization

- Text Mining & Regular Expressions

---

## Why Would a Historian Want to Program? 


- Access to Data Sources (**A**pplication **P**rogramming **I**nterfaces) 

- Visualization

- Text Mining & Regular Expressions

- Reproducibility



---


## Why Would a Historian Want to Program? 


- Access to Data Sources (**A**pplication **P**rogramming **I**nterfaces) 

- Visualization

- Text Mining & Regular Expressions

- Reproducibility

- Code as Communication Channel

- ...


---

## Background Poll

<iframe src="http://127.0.0.1:1234" width="900px" height="450px"></iframe>

---

## Check Your Stack

- R 3.5.1+
- R Studio 1.2.1335+
- git (optional)

---

## Summary: Introduction to the R Studio IDE

- R is **NOT** R Studio
- 4 Panes
- script window vs. console
- cmd + enter (osx), ctrl + enter (PC) runs selected command
- ctrl 1,2 switches between console and script
- R Studio Cheat Sheets
- use Projects (.Rproj)! 


---

## Summary: R Basics 

- Assignment operator '<-'
- '#' starts a comment. 
- important base R types: vector, matrix, data.frame, list
- Read code from the inside out
- learn basic syntax, understand the rest 
- the **tidyverse** and **data.table** are frameworks of their within R
- [CRAN](https://cran.r-project.org) is the Official R (package) repository. 

---


## Are You Ready?

1. Of what data type is the built-in dataset *mtcars*
2. Create vector containing three integers.
3. Create a 2x2 matrix of integers.
4. Create a data.frame that contains a column of letters and 
a column of integers.
5. Create a list that contains all elements produced in tasks 2-4
6. Install a package from CRAN and load the library. 


---

## Resources

- ?function_name calls R documentation
- [Official Introduction to R](https://cran.r-project.org/doc/manuals/R-intro.pdf) ( chapter 2)
- [Stackoverflow questions tagged R](http://stackoverflow.com/questions/tagged/r)
- [Achim Zeileis: Introduction to R](https://eeecon.uibk.ac.at/~zeileis/teaching/R-Intro/)
- [CRAN](https://cran.r-project.org)
- [CRAN Task Views (CTV)](https://cran.r-project.org/web/views/)








